# Generated by Django 3.0.4 on 2020-07-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocr',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
